config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|zh/ do

    get 'welcome/index'

    resources :foods
    resources :shops
    resources :communities
    resources :events
    resources :pictures
    resources :videos
    resources :services
    resources :businesses
    root 'welcome#index'
  end
  get '/*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}/")

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy, autosave: true
  has_many :categories, :dependent => :destroy, autosave: true
  accepts_nested_attributes_for :pictures, :reject_if => lambda { |a| a[:image].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :categories, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  has_attached_file :image, styles: { medium: "300x300>", small: "200x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all.order(:name)
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to shops_path
    else
      render :new
    end
  end

  def new
    @shop = Shop.new
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def show
    @shop = Shop.friendly.find(params[:id])
  end

  def update
    @shop = Shop.friendly.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shop_path(@shop)
    else
      render :edit
    end
  end

  def destroy
  end

  private
  def shop_params
    params.require(:shop).permit(:name, :address, :phone, :yelp, :image, :bio, :category, :youtube, :pictures_attributes => [:image])
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= render "layouts/errors", :object => @shop %>

<%= form_for @shop, html: { multipart: true } do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :address %>:
  <%= f.text_field :address %><br />

  <%= f.file_field :image %>

  <%= f.submit %>
<% end %>

app/views/shops/edit.html.erb
<h1>Shops#edit</h1>
<p>Find me in app/views/shops/edit.html.erb</p>

<%= render 'form' %>

app/views/shops/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="carousel-image-center img-responsive"src="/assets/pdxasialogo2.png" alt="Chania">
        </div>

        <div class="item">
          <img class="carousel-image-center img-responsive"src="/assets/pdxasialogo2.png" alt="Chania">
        </div>

        <div class="item">
          <img class="carousel-image-center img-responsive"src="/assets/pdxasialogo2.png" alt="Flower">
        </div>

        <div class="item">
          <img class="carousel-image-center img-responsive"src="/assets/pdxasialogo2.png" alt="Flower">
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>
<!-- <div class="demographic-statistics">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2 stat-div">
        <h4>Hi, Friend!</h4>
      </div>
      <div class="col-md-2 stat-div">
        <div class="stat-text">
          Asians in Portland Metro
        </div>
        <div class="stat-number">
          7.6%
        </div>
      </div>
      <div class="col-md-2 stat-div">
        <div class="stat-text">
          Total Asians
        </div>
        <div class="stat-number">
          134,726
        </div>
      </div>
      <div class="col-md-2 stat-div">
        <div class="stat-text">
          General Population
        </div>
        <div class="stat-number">
          1,766,135
        </div>
      </div>
      <div class="col-md-2 stat-div">
        <div class="stat-text">
          2015 Asian Growth
        </div>
        <div class="stat-number">
          4.5%
        </div>
      </div>
      <div class="col-md-2 stat-div">
        <div class="stat-text">
          2015 Total Population Growth
        </div>
        <div class="stat-number">
          1.5%
        </div>
      </div>
      <div class="col-md-2 stat-div">
        <div class="stat-text">
          2014 Asian Growth
        </div>
        <div class="stat-number">
          4.7%
        </div>
      </div>
      <div class="col-md-2 stat-div">
        <div class="stat-text">
          2014 Total Population Growth
        </div>
        <div class="stat-number">
          1.1%
        </div>
      </div>
      <div class="col-md-2 stat-div">
        <div class="stat-text">
          Oregon Population
        </div>
        <div class="stat-number">
          4,028,977
        </div>
      </div>
    </div>
  </div>
</div> -->
<div class="container-fluid restaurants-row">
  <div id="food-row" class="row">
    <% @shops.each do |shop| %>
      <div class="col-md-2 col-xs-4">
        <div class="food-item">
          <div class="food-image">
            <%= link_to shop_path(shop) do %>
              <%= image_tag(shop.image.url(:small), class: "food-image-tag") %>
            <% end %>
          </div>
          <div class="food-text">
            <%= link_to shop.name, shop_path(shop) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/new.html.erb
<h1>Shops#new</h1>
<p>Find me in app/views/shops/new.html.erb</p>

<%= render 'form' %>

app/views/shops/show.html.erb
<div class="container-fluid no-padding">
  <div class="banner-section">
    <div class="food-bg-wrap">
      <div class="food-background img-responsive" style="background-image: url(<%= @shop.image %>);">
      </div>
    </div>
    <div class="food-title">
      <%= @shop.name %>
    </div>
    <div class="breadcrumbs">
      <%= render_breadcrumbs :separator => ' > ' %>
    </div>
  </div>
</div>
<div class="container-fluid no-padding">
  <div class="row no-margin">
    <div class="col-xs-12 col-md-offset-1 col-md-10">
      <div id="owl-carousel">
        <div class="item img-responsive">
          <%= image_tag @shop.image.url(:small) %>
        </div>
        <% @shop.pictures.each do |picture| %>
          <div class="item img-responsive">
            <%= image_tag(picture.image.url(:small)) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<div class="container">
  <div class="col-md-4">
    <div class="well">
      <p class="shop-title">
        <%= @shop.name %>
      </p>
      <p class="shop-address">
        <%= @shop.address %>
      </p>
      <p>
        <%= @shop.bio %>
      </p>
      <%= link_to @shop.yelp, @shop.yelp %>
      <br>
      <%= link_to "Edit", edit_shop_path(@shop) %>
      <br>
      <!-- <p>
        <%= link_to "Delete", food_path(@shop), method: :delete, data: { confirm: "Are you sure you want to delete?"} %>
      </p> -->
    </div>
    <div class="well">
      <h4>Tags</h4>
      <% @shop.categories.each_with_index do |category, idx| %>
        <% if idx > 0 %>
          |
        <% end %>
        <%= category.name %>
      <% end %>
    </div>
  </div>
  <div class="col-md-8">
    <div class="well">
      <div class="video-container">
        <iframe width="560" height="315" src="<%= @shop.youtube %>" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
    <div class="well">
      <h4>About</h4>
      <%= @shop.bio %>
    </div>
    <div class="well">
      <h4>Tags</h4>
      <%= @shop.categories.map(&:name).join(' | ') %>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $("#owl-carousel").owlCarousel({
            autoPlay: 3000,
            items : 5,
            itemsDesktop : [1119,5],
            itemsDesktopSmall : [979, 5]
        });
    });
</script>