config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|zh/ do

    get 'welcome/index'

    resources :foods
    resources :shops
    resources :communities
    resources :events
    resources :pictures
    resources :videos
    resources :services
    resources :businesses
    root 'welcome#index'
  end
  get '/*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}/")

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # before_action :set_locale

  def index
    # @foods = Food.all.limit(12)
    @foods = Food.joins('INNER JOIN food_translations ON foods.id=food_translations.food_id').order('food_translations.name').where('food_translations.locale=?', params[:locale]).limit(3)
    # @foods = Food.all.order(:name).limit(12)
    @communities = Community.all.order(:name)
    @shops = Shop.all.order(:name).limit(3)
    @eventsbox = Event.all.limit(3)
    @events = Event.all
    @services = Service.all.limit(3)
  end

  # def set_locale
  #   if params[:locale] == nil
  #     params[:locale] = I18n.locale
  #     I18n.locale = :en
  #   else
  #     I18n.locale = :zh
  #   end
  # end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<br>
<div class="container">
  <header class="jumbotron hero-spacer">
    <h1>Portland ASIA</h1>
    <p>All of Portland's Asian restaurants, businesses, communities in one place</p>
  </header>
</div>
<div class="container">
  <h1 class="upcoming-events">Featured <span class="font-blue">Videos</span></h1>
  <div class="row">
    <div class="col-md-6 col-xs-6">
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/sWWP-OaJ6Y0" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
    <div class="col-md-6 col-xs-6">
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/wFGCr9KsqUA" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-xs-6">
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/JabHNeYf2t8" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
    <div class="col-md-6 col-xs-6">
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/usA4poeCsdo" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <h1 class="upcoming-events">Restaurant <span class="font-blue">Videos</span></h1>
  <div class="row">
    <div class="col-md-3 col-xs-6">
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/usA4poeCsdo" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
    <div class="col-md-3 col-xs-6">
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/BTD_Ix1dpLU" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
    <div class="col-md-3 col-xs-6">
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/87nd5U1x5WY" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
    <div class="col-md-3 col-xs-6">
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/7Dp75GmyO6M" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>
<!-- <div class="container">
  <h1 class="upcoming-events">Upcoming <span class="font-blue">Events</span></h1>
  <% @eventsbox.each do |event| %>
    <div class="col-md-4 col-sm-4 col-xs-4 fp-event-box">
      <%= link_to event_path(event), class:"link-margin" do %>
        <%= image_tag(event.image.url(:small), class: "event-image") %>
      <% end %>
      <div class="event-date-box">
        <strong><%= event.date.strftime("%^b %e") %></strong> - <small><%=h truncate(event.name, length: 20) %></small>
      </div>
    </div>
  <% end %>
</div>
<br>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
        <div class="fp-well">
          <h1 class="upcoming-events-small">Featured <span class="font-blue">Food</span></h1>
          <% @foods.each do |food| %>
          <%=h link_to truncate(food.name, length: 50), food_path(food) %>
          <br>
          <% end %>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
        <div class="fp-well">
          <h1 class="upcoming-events-small">Featured <span class="font-blue">Shop</span></h1>
          <% @shops.each do |shop| %>
          <%=h link_to truncate(shop.name, length: 50), shop_path(shop) %>
          <br>
          <% end %>
        </div>
      </div>

      <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
        <div class="fp-well-last">
          <h1 class="upcoming-events-small">Featured <span class="font-blue">People</span></h1>
          <% @services.each do |service| %>
          <%=h link_to truncate(service.set_fullname, length: 50), service_path(service) %>
          <br>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<br> -->

<div class="container">
  <h1 class="upcoming-events">Upcoming <span class="font-blue">Events</span></h1>
  <div class="row">
    <div class="event-header">
      <%= button_to "Post An Event", new_event_path, :class => "post-event-button", :method => :get %>
      <p class="display-inline font-italic">
        Where to go out, dance, and revel. Hand-picked events in Portland, curated by a team with combined decades in town.
      </p>
    </div>
  </div>
  <div class="row event-bar">
    <div class="col-md-12">

      <a href="/events">
        <div class="col-md-2 col-xs-2 event-box">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            ALL EVENTS
          </p>
        </div>
      </a>
      <a href="/foods">
        <div class="col-md-2 col-xs-2 event-box">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            SPORTS
          </p>
        </div>
      </a>
      <a href="/foods">
        <div class="col-md-2 col-xs-2 event-box">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            DINING
          </p>
        </div>
      </a>
      <a href="/foods">
        <div class="col-md-2 col-xs-2 event-box">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            COMMUNITY
          </p>
        </div>
      </a>
      <a href="/foods">
        <div class="col-md-2 col-xs-2 event-box">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            ARTS
          </p>
        </div>
      </a>
      <a href="/foods">
        <div class="col-md-2 col-xs-2 event-box no-border">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            NIGHTLIFE
          </p>
        </div>
      </a>
    </div>
  </div>
  <div class="row">
    <p class="display-inline">
      Date
    </p>
    <input class="display-inline" type="text_field" name="name" value="" placeholder="DATE">
  </div>
  <div class="row">
    <div class="col-md-8">
      <% @events.each do |event| %>
        <div class="well">
          <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-4">
              <div class="">
                <%= event.date.strftime("%B") %>
                <span class="date-font">
                  <%= event.date.strftime("%e") %>
                </span>
              </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-4">
              <div class="event-image">
                <%= link_to event_path(event) do %>
                  <%= image_tag(event.image.url(:thumb)) %>
                <% end %>
              </div>
            </div>
            <div class="col-md-8 col-sm-6 col-xs-12">
              <p class="event-title">
                <%= link_to event.name, event_path(event) %>
              </p>
              <%= event.location %>
              <br>
              <%= event.description %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <div class="well">
        Stuff
      </div>
    </div>
  </div>
</div>

<div class="container" style="text-align: center;">
  <%= social_share_button_tag("Portland Asia - Events, news, all things Asian in Portland", :url => "http://www.portlandasia.com") %>
</div>
<br>