config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|zh/ do

    get 'welcome/index'

    resources :foods
    resources :shops
    resources :communities
    resources :events
    resources :pictures
    resources :videos
    resources :services
    resources :businesses
    root 'welcome#index'
  end
  get '/*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}/")

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_attached_file :image, styles: { large: "640x360", medium: "300x300#", small: "200x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all.order(:date)
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.friendly.find(params[:id])

  end

  private
  def event_params
    params.require(:event).permit(:name, :location, :date, :description, :image)
  end

end

app/views/events/_form.html.erb
<%= render "layouts/errors", :object => @event %>

<%= form_for @event, html: { multipart: true } do |f| %>
  <%= f.label :name %>:
  <br>
  <%= f.text_field :name %><br />

  <%= f.label :location %>:
  <br>
  <%= f.text_field :location %><br />
  <br>
  <%= f.date_select :date %>
  <br>
  <br>
  <%= f.label :description %>
  <br>
  <%= f.text_area :description %>
  <br>
  <br>
  <%= f.label :image %>: Cover Photo
  <%= f.file_field :image %>
  <br>
  <%= f.submit %>
<% end %>

app/views/events/index.html.erb
<div id="banner">

</div>
<div id="events">

</div>
<div class="container">
  <div class="row">
    <h1 class="upcoming-events">Upcoming <span class="font-blue">Events</span></h1>
    <div class="event-header">
      <%= button_to "Post An Event", new_event_path, :class => "post-event-button", :method => :get %>
      <p class="display-inline font-italic">
        Where to go out, dance, and revel. Hand-picked events in Portland, curated by a team with combined decades in town.
      </p>
    </div>
  </div>
  <div class="row event-bar">
    <div class="col-md-12">

      <a href="/events">
        <div class="col-md-2 col-xs-2 event-box">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            ALL EVENTS
          </p>
        </div>
      </a>
      <a href="/foods">
        <div class="col-md-2 col-xs-2 event-box">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            SPORTS
          </p>
        </div>
      </a>
      <a href="/foods">
        <div class="col-md-2 col-xs-2 event-box">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            DINING
          </p>
        </div>
      </a>
      <a href="/foods">
        <div class="col-md-2 col-xs-2 event-box">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            COMMUNITY
          </p>
        </div>
      </a>
      <a href="/foods">
        <div class="col-md-2 col-xs-2 event-box">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            ARTS
          </p>
        </div>
      </a>
      <a href="/foods">
        <div class="col-md-2 col-xs-2 event-box no-border">
          <i class="fa fa-home font-30" aria-hidden="true"></i>
          <p>
            NIGHTLIFE
          </p>
        </div>
      </a>
    </div>
  </div>
  <div class="row">
    <p class="display-inline">
      Date
    </p>
    <input class="display-inline" type="text_field" name="name" value="" placeholder="DATE">
  </div>
  <div class="row">
    <div class="col-md-8">
      <% @events.each do |event| %>
        <div class="well">
          <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-4">
              <div class="">
                <%= event.date.strftime("%B") %>
                <span class="date-font">
                  <%= event.date.strftime("%e") %>
                </span>
              </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-4">
              <div class="event-image">
                <%= link_to event_path(event) do %>
                  <%= image_tag(event.image.url(:thumb)) %>
                <% end %>
              </div>
            </div>
            <div class="col-md-8 col-sm-6 col-xs-12">
              <p class="event-title">
                <%= link_to event.name, event_path(event) %>
              </p>
              <%= event.location %>
              <br>
              <%= event.description %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <div class="well">
        Stuff
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="col-md-4">
    <div class="well">
      <h4>Contact</h4>
      <%= @event.name %>
      <br>
      <%= @event.location %>
      <br>
      <%= @event.date %>
      <br>
      <%= @event.description %>
      <br>
      <%= link_to "Edit", edit_event_path(@event) %>
      <br>
      <!-- <p>
        <%= link_to "Delete", food_path(@event), method: :delete, data: { confirm: "Are you sure you want to delete?"} %>
      </p> -->
    </div>
  </div>
</div>