config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|zh/ do

    get 'welcome/index'

    resources :foods
    resources :shops
    resources :communities
    resources :events
    resources :pictures
    resources :videos
    resources :services
    resources :businesses
    root 'welcome#index'
  end
  get '/*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}/")

end

app/models/business.rb
class Business < ActiveRecord::Base
  has_attached_file :image, styles: { large: "300x400#", medium: "300x300#", small: "200x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :food
	belongs_to :shop
	belongs_to :event
end

app/models/community.rb
class Community < ActiveRecord::Base
	has_many :pictures, :dependent => :destroy, autosave: true
	accepts_nested_attributes_for :pictures, :reject_if => lambda { |a| a[:image].blank? }, :allow_destroy => true
  has_attached_file :image, styles: { medium: "300x300>", small: "200x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	extend FriendlyId
	friendly_id :name, use: :slugged
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_attached_file :image, styles: { large: "640x360", medium: "300x300#", small: "200x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/food.rb
class Food < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy, autosave: true
  accepts_nested_attributes_for :pictures, :reject_if => lambda { |a| a[:image].blank? }, :allow_destroy => true
  has_attached_file :image, styles: { medium: "300x300>", small: "200x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  translates :name, :bio, :fallbacks_for_empty_translations => true

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :food
	belongs_to :community
  belongs_to :shop
  has_attached_file :image, styles: { medium: "300x300>", small: "200x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_attached_file :image, styles: { large: "300x400#", medium: "300x300#", small: "200x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  before_save :set_fullname
  before_update :set_fullname

  extend FriendlyId
  friendly_id :set_fullname, use: :slugged

  def set_fullname
    fullname = "#{first} #{last}"
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy, autosave: true
  has_many :categories, :dependent => :destroy, autosave: true
  accepts_nested_attributes_for :pictures, :reject_if => lambda { |a| a[:image].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :categories, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  has_attached_file :image, styles: { medium: "300x300>", small: "200x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all.order(:date)
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.friendly.find(params[:id])

  end

  private
  def event_params
    params.require(:event).permit(:name, :location, :date, :description, :image)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Foods", :foods_path

  def index
    # @foods = Food.all.order(:name)
    @foods = Food.joins('INNER JOIN food_translations ON foods.id=food_translations.food_id').order('food_translations.name').where('food_translations.locale=?', params[:locale])

    add_breadcrumb "index", foods_path
  end

  def create
    @food = Food.new(food_params)
    respond_to do |format|
      if @food.save
        if params[:images]
          params[:images].each { |image|
            @food.pictures.create(image: image)
          }
        end
        format.html { redirect_to @food, notice: 'Gallery was successfully created.' }
        format.json { render json: @food, status: :created, location: @food }
      else
        render :new
      end
    end
  end

  def new
    @food = Food.new
    5.times { @food.pictures.build }
  end

  def edit
    @food = Food.find(params[:id])
    5.times { @food.pictures.build }
  end

  def show
    @food = Food.friendly.find(params[:id])

    add_breadcrumb @food.name, food_path([:id])
  end

  def update
    @food = Food.friendly.find(params[:id])
    if @food.update(food_params)
      redirect_to food_path(@food)
    else
      render :edit
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :address, :phone, :image, :yelp, :bio, :category, :youtube, :pictures_attributes => [:image])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all.order(:name)
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to shops_path
    else
      render :new
    end
  end

  def new
    @shop = Shop.new
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def show
    @shop = Shop.friendly.find(params[:id])
  end

  def update
    @shop = Shop.friendly.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shop_path(@shop)
    else
      render :edit
    end
  end

  def destroy
  end

  private
  def shop_params
    params.require(:shop).permit(:name, :address, :phone, :yelp, :image, :bio, :category, :youtube, :pictures_attributes => [:image])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @foods = Food.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # before_action :set_locale

  def index
    # @foods = Food.all.limit(12)
    @foods = Food.joins('INNER JOIN food_translations ON foods.id=food_translations.food_id').order('food_translations.name').where('food_translations.locale=?', params[:locale]).limit(3)
    # @foods = Food.all.order(:name).limit(12)
    @communities = Community.all.order(:name)
    @shops = Shop.all.order(:name).limit(3)
    @eventsbox = Event.all.limit(3)
    @events = Event.all
    @services = Service.all.limit(3)
  end

  # def set_locale
  #   if params[:locale] == nil
  #     params[:locale] = I18n.locale
  #     I18n.locale = :en
  #   else
  #     I18n.locale = :zh
  #   end
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_errors.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <% if object.errors.any? %>
      <h3>Please fix these errors:</h3>
      <ul>
        <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= if content_for?(:title) then yield(:title) + ' | ' end %>
    Portland ASIA
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
  <link rel="icon" href="/favicon.png">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="description" content="Portland ASIA is the largest online site for the Asian community in Portland, OR for food, shopping, events, and people. ">
  <meta name=viewport content="width=device-width, initial-scale=1">
  <%= analytics_init if GoogleAnalytics.valid_tracker? %>
</head>
<body>
  <div id="wrapper">

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li class="sidebar-brand">
          <a href="#">
            Menu
          </a>
        </li>
        <li>
          <%= link_to foods_path do %>
          <i class="fa fa-cutlery" aria-hidden="true"></i> <%= t('layouts.application.food') %>
          <% end %>
        </li>
        <li>
          <%=link_to events_path do %>
          <i class="fa fa-calendar" aria-hidden="true"></i> <%= t('layouts.application.event') %>
          <% end %>
        </li>
        <li>
          <%= link_to shops_path do %>
          <i class="fa fa-shopping-bag" aria-hidden="true"></i> <%= t('layouts.application.shop') %>
          <% end %>
        </li>
        <li>
          <%= link_to communities_path do %>
          <i class="fa fa-lightbulb-o" aria-hidden="true"></i> <%= t('layouts.application.community') %>
          <% end %>
        </li>
        <li>
          <%= link_to pictures_path do %>
          <i class="fa fa-camera" aria-hidden="true"></i> <%= t('layouts.application.picture') %>
          <% end %>
        </li>
        <li>
          <%= link_to videos_path do %>
          <i class="fa fa-video-camera" aria-hidden="true"></i> <%= t('layouts.application.video') %>
          <% end %>
        </li>
        <li>
          <%= link_to services_path do %>
          <i class="fa fa-video-camera" aria-hidden="true"></i> <%= t('layouts.application.service') %>
          <% end %>
        </li>
        <li>
          <%= link_to "EN", locale: "en" %>
        </li>
        <li>
          <%= link_to "中文", locale: "zh" %>
        </li>
      </ul>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
      <nav class="navbar-default navbar-fixed-top">

        <div class="container">
          <div class="row div-nav">
            <div class="col-lg-12">
              <a href="#menu-toggle" class="btn btn-default btn-nav" id="menu-toggle"><i class="fa fa-bars" aria-hidden="true"></i></a>
              <a class="navbar-logo" href="/"><i class="fa fa-cog fa-spin fa-3x fa-fw"></i>
                <span class="sr-only">Loading...</span> Portland <span>A</span><span class="orange-logo">S</span><span class="yellow-logo">I</span><span>A</span> </a>
              </div>
              <div class="row home-nav">
                <ul>
                  <li><a href="#news">Blog</a></li>
                  <li><a href="#news">News</a></li>
                  <li><a href="/foods">Food</a></li>
                  <li><a href="/services">People</a></li>
                  <li><a href="/businesses">Businesses</a></li>
                </ul>
              </div>
            </div>
          </div>
        </nav>
        <%= yield %>
        <footer class="text-center">
          <div class="footer-above">
            <div class="container">
              <div class="row">
                <div class="footer-col col-md-4">
                  <h3>Location</h3>
                  <p>12345 SE Happy Valley Drive
                    <br>Portland, OR 97086</p>
                  </div>
                  <div class="footer-col col-md-4">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                      <li>
                        <a href="#" class="btn-social btn-outline"><span class="sr-only">Facebook</span><i class="fa fa-fw fa-facebook"></i></a>
                      </li>
                      <li>
                        <a href="#" class="btn-social btn-outline"><span class="sr-only">Google Plus</span><i class="fa fa-fw fa-google-plus"></i></a>
                      </li>
                      <li>
                        <a href="#" class="btn-social btn-outline"><span class="sr-only">Twitter</span><i class="fa fa-fw fa-twitter"></i></a>
                      </li>
                      <li>
                        <a href="#" class="btn-social btn-outline"><span class="sr-only">Linked In</span><i class="fa fa-fw fa-linkedin"></i></a>
                      </li>
                      <li>
                        <a href="#" class="btn-social btn-outline"><span class="sr-only">Dribble</span><i class="fa fa-fw fa-dribbble"></i></a>
                      </li>
                    </ul>
                  </div>
                  <div class="footer-col col-md-4">
                    <h3>About Portland ASIA</h3>
                    <p>Portland ASIA is the largest online community of Asian businesses in Portland.</a></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="footer-below">
              <div class="container">
                <div class="row">
                  <div class="col-lg-12">
                    Copyright &copy; Portland ASIA 2017
                  </div>
                </div>
              </div>
            </div>
          </footer>
      </div>
    </div>
    <!-- /#page-content-wrapper -->
  </div>

  <script src="js/jquery.js"></script>

  <script>
  $("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
  });
  </script>



</body>
</html>

app/views/layouts/test.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div id="wrapper">
      <div class="overlay"></div>

      <!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
          <ul class="nav sidebar-nav">
              <li class="sidebar-brand">
                  <a href="#">
                     Portland Asia
                  </a>
              </li>
              <li>
                  <a href="#">Home</a>
              </li>
              <li>
                  <a href="#">About</a>
              </li>
              <li>
                <%= link_to pictures_path do %>
                <i class="fa fa-camera" aria-hidden="true"></i> <%= t('layouts.application.picture') %>
                <% end %>
              </li>
              <li>
                <%= link_to videos_path do %>
                <i class="fa fa-video-camera" aria-hidden="true"></i> <%= t('layouts.application.video') %>
                <% end %>
              </li>
              <li>
                  <a href="#">Events</a>
              </li>
              <li>
                  <a href="#">Team</a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li class="dropdown-header">Dropdown heading</li>
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              <li>
                  <a href="#">Services</a>
              </li>
              <li>
                  <a href="#">Contact</a>
              </li>
              <li>
                  <a href="https://twitter.com/maridlcrmn">Follow me</a>
              </li>
          </ul>
      </nav>
      <!-- /#sidebar-wrapper -->

      <!-- Page Content -->
      <div id="page-content-wrapper">
          <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
              <span class="hamb-top"></span>
        <span class="hamb-middle"></span>
      <span class="hamb-bottom"></span>
          </button>
      </div>
      <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <div class="navbar-header">
    <!-- <a class="navbar-brand" href="/"><img class="pdxasialogo img-responsive" src="/assets/pdxasialogo1.png" alt="" /></a> -->
    <a class="navbar-logo" href="/">Portland <span>A</span><span class="orange-logo">S</span><span class="yellow-logo">I</span><span>A</span> </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li>
      <%= link_to foods_path do %>
        <i class="fa fa-cutlery" aria-hidden="true"></i> <%= t('layouts.application.food') %>
        <% end %>
      </li>
      <li>
        <%=link_to events_path do %>
        <i class="fa fa-calendar" aria-hidden="true"></i> <%= t('layouts.application.event') %>
        <% end %>
      </li>
      <li>
        <%= link_to shops_path do %>
        <i class="fa fa-shopping-bag" aria-hidden="true"></i> <%= t('layouts.application.shop') %>
        <% end %>
      </li>
      <li>
        <%= link_to communities_path do %>
        <i class="fa fa-lightbulb-o" aria-hidden="true"></i> <%= t('layouts.application.community') %>
        <% end %>
      </li>
      <li>
        <%= link_to services_path do %>
        <i class="fa fa-video-camera" aria-hidden="true"></i> <%= t('layouts.application.service') %>
        <% end %>
      </li>
      <li>
        <%= link_to "EN", locale: "en" %>
      </li>
      <li>
        <%= link_to "中文", locale: "zh" %>
      </li>

      <!-- <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li> -->
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li class="social-links"><a href="/"><i class="fa fa-home font-25" aria-hidden="true"></i></a></li>
          <li class="social-links"><a href="https://www.facebook.com/pdxasia/"><i class="fa fa-facebook-square font-25" aria-hidden="true"></i></a></li>
          <li class="social-links"><a href="https://www.instagram.com/pdxasia/"><i class="fa fa-instagram font-25" aria-hidden="true"></i></a></li>
          <li class="social-links"><a href="https://twitter.com/portlandasia"><i class="fa fa-twitter font-25" aria-hidden="true"></i></a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul> -->
      </li>
      <li class="social-links"><a href="/"><i class="fa fa-home font-25" aria-hidden="true"></i></a></li>
      <li class="social-links"><a href="https://www.facebook.com/pdxasia/"><i class="fa fa-facebook-square font-25" aria-hidden="true"></i></a></li>
      <li class="social-links"><a href="https://www.instagram.com/pdxasia/"><i class="fa fa-instagram font-25" aria-hidden="true"></i></a></li>
      <li class="social-links"><a href="https://twitter.com/portlandasia"><i class="fa fa-twitter font-25" aria-hidden="true"></i></a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>